import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getPlaiceholder } from 'plaiceholder'

export const getStaticProps = async () => {
  const urls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 5, 7, 8, 2, 4, 9, 6].map((u) => `/${u}.jpg`)

  const images = await Promise.all(
    urls.map(async (url) => {
      const { base64, img } = await getPlaiceholder(url);

      return {
        ...img,
        alt: "image",
        width: "100",
        height: "400",
        unoptimized: true,
        key: url,
        objectFit: "cover",
        placeholder: "blur",
        blurDataURL: base64,
      }
    })
  ).then((values) => values);
  
  return {
    props: {
        images,
    }
  }
}

const Item = ({ ...props }) => {
  return <Image {...props} />
}

const Items = ({ images }) => {
  console.log(images)
  return (
    <div>
      {images.map((image) => <Item { ...image } />)}
    </div>
  )
}

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <Items { ...props } />
      </main>
    </div>
  )
}

export default Home
